"""
MERMAID GENERATOR TAB
====================
Scans papers for semantic tags, generates mermaid diagrams:
- Inline mermaid before semantic mapping section
- Large PNG export to O:\00_MEDIA\Mermaid
- Master combined diagram for all axioms
"""

import os
import re
from pathlib import Path
from datetime import datetime
from typing import Optional, List, Dict

from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QGroupBox, QPushButton,
    QLabel, QLineEdit, QFileDialog, QProgressBar, QTextEdit,
    QTableWidget, QTableWidgetItem, QCheckBox, QMessageBox,
    QHeaderView, QSplitter
)
from PySide6.QtCore import Qt, QThread, Signal
from PySide6.QtGui import QFont


class MermaidWorker(QThread):
    """Background worker for mermaid generation."""
    progress = Signal(int, int, str)  # current, total, message
    file_done = Signal(str, bool, str)  # filename, success, message
    finished = Signal(int, int)  # successful, total
    
    def __init__(self, generator, folder_path: str, inject_inline: bool = True, export_png: bool = True):
        super().__init__()
        self.generator = generator
        self.folder_path = folder_path
        self.inject_inline = inject_inline
        self.export_png = export_png
        self._stop = False
    
    def stop(self):
        self._stop = True
    
    def run(self):
        folder = Path(self.folder_path)
        md_files = list(folder.rglob("*.md"))
        total = len(md_files)
        successful = 0
        
        for i, md_file in enumerate(md_files):
            if self._stop:
                break
            
            self.progress.emit(i + 1, total, md_file.name)
            
            try:
                # Extract tags
                tags = self.generator.extract_tags(md_file)
                
                if not tags:
                    self.file_done.emit(md_file.name, False, "No semantic tags")
                    continue
                
                # Generate mermaid code
                title = md_file.stem.replace('_', ' ')
                inline = self.generator.generate_inline_mermaid(tags, title)
                
                png_path = None
                if self.export_png:
                    mermaid_code = self.generator.generate_mermaid_code(tags, title)
                    png_path = self.generator.export_to_png(mermaid_code, md_file.stem)
                
                # Inject inline mermaid into the file
                if self.inject_inline and inline:
                    self._inject_mermaid_to_file(md_file, inline, png_path)
                
                successful += 1
                msg = f"{len(tags)} tags"
                if png_path:
                    msg += f" | PNG: {png_path.name}"
                self.file_done.emit(md_file.name, True, msg)
                
            except Exception as e:
                self.file_done.emit(md_file.name, False, str(e))
        
        self.finished.emit(successful, total)
    
    def _inject_mermaid_to_file(self, filepath: Path, inline: str, png_path: Optional[Path] = None):
        """Inject mermaid diagram before semantic mapping section."""
        content = filepath.read_text(encoding='utf-8', errors='ignore')
        
        # Build the section to inject
        section = "\n\n---\n\n## 🔗 Dependency Graph\n\n"
        if png_path and png_path.exists():
            section += f"📊 **[Full Size PNG]({png_path})**\n\n"
        section += inline + "\n"
        
        # Find injection point - before semantic tags or at end
        # Look for "## Semantic" or "%%tag::" or end of file
        
        # Check if already has dependency graph
        if "## 🔗 Dependency Graph" in content or "## Dependency Graph" in content:
            # Replace existing
            content = re.sub(
                r'## 🔗 Dependency Graph.*?(?=\n## |\n---\n\n## |\Z)',
                section.strip() + "\n",
                content,
                flags=re.DOTALL
            )
        else:
            # Find best insertion point
            patterns = [
                r'## Semantic Mapping',
                r'%%tag::',
                r'\*Generated by',
                r'---\s*$'
            ]
            
            inserted = False
            for pattern in patterns:
                match = re.search(pattern, content)
                if match:
                    pos = match.start()
                    content = content[:pos] + section + content[pos:]
                    inserted = True
                    break
            
            if not inserted:
                content += section
        
        filepath.write_text(content, encoding='utf-8')


class MermaidTab(QWidget):
    """Mermaid Generator Tab - scans papers and generates dependency graphs."""
    
    def __init__(self, settings_mgr, mermaid_engine):
        super().__init__()
        self.settings_mgr = settings_mgr
        self.mermaid_engine = mermaid_engine
        self.worker = None
        self._results = []
        
        self._init_ui()
    
    def _init_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(24, 24, 24, 24)
        layout.setSpacing(16)
        
        # Header
        header = QLabel("🎨 Mermaid Dependency Graphs")
        header.setStyleSheet("font-size: 20px; font-weight: bold; color: #00d9ff;")
        layout.addWidget(header)
        
        desc = QLabel("Scans papers for semantic tags (%%tag::...) and generates visual dependency graphs.")
        desc.setStyleSheet("color: #888; margin-bottom: 8px;")
        layout.addWidget(desc)
        
        # === FOLDER SELECTION ===
        folder_box = QGroupBox("📁 Papers Folder")
        folder_layout = QVBoxLayout(folder_box)
        
        folder_row = QHBoxLayout()
        self.folder_edit = QLineEdit()
        self.folder_edit.setPlaceholderText("Select folder containing papers...")
        
        # Default to Logos Papers folder
        default_path = r"O:/Theophysics_Master/TM SUBSTACK/03_PUBLICATIONS/Logos Papers Axiom"
        if Path(default_path).exists():
            self.folder_edit.setText(default_path)
        
        browse_btn = QPushButton("Browse")
        browse_btn.clicked.connect(self._browse_folder)
        
        folder_row.addWidget(self.folder_edit, 1)
        folder_row.addWidget(browse_btn)
        folder_layout.addLayout(folder_row)
        
        layout.addWidget(folder_box)
        
        # === OPTIONS ===
        options_box = QGroupBox("⚙️ Options")
        options_layout = QHBoxLayout(options_box)
        
        self.inject_check = QCheckBox("Inject inline mermaid into papers")
        self.inject_check.setChecked(True)
        self.inject_check.setToolTip("Add mermaid diagram before semantic mapping section")
        options_layout.addWidget(self.inject_check)
        
        self.png_check = QCheckBox("Export large PNG to O:\\00_MEDIA\\Mermaid")
        self.png_check.setChecked(True)
        self.png_check.setToolTip("Export high-resolution PNG for each paper")
        options_layout.addWidget(self.png_check)
        
        self.recursive_check = QCheckBox("Include subfolders")
        self.recursive_check.setChecked(True)
        options_layout.addWidget(self.recursive_check)
        
        options_layout.addStretch()
        layout.addWidget(options_box)
        
        # === ACTIONS ===
        actions_box = QGroupBox("🚀 Actions")
        actions_layout = QVBoxLayout(actions_box)
        
        btn_row = QHBoxLayout()
        
        self.scan_btn = QPushButton("🔍 Scan & Generate All")
        self.scan_btn.setObjectName("primaryBtn")
        self.scan_btn.clicked.connect(self._start_scan)
        btn_row.addWidget(self.scan_btn)
        
        self.combine_btn = QPushButton("🔗 Combine All to Master")
        self.combine_btn.clicked.connect(self._combine_all)
        self.combine_btn.setToolTip("Merge all diagrams into one master graph")
        btn_row.addWidget(self.combine_btn)
        
        self.stop_btn = QPushButton("⏹️ Stop")
        self.stop_btn.clicked.connect(self._stop_scan)
        self.stop_btn.setEnabled(False)
        btn_row.addWidget(self.stop_btn)
        
        btn_row.addStretch()
        
        self.open_media_btn = QPushButton("📂 Open Media Folder")
        self.open_media_btn.clicked.connect(self._open_media_folder)
        btn_row.addWidget(self.open_media_btn)
        
        actions_layout.addLayout(btn_row)
        
        # Progress
        self.progress_bar = QProgressBar()
        self.progress_bar.setVisible(False)
        actions_layout.addWidget(self.progress_bar)
        
        self.status_label = QLabel("Ready")
        self.status_label.setStyleSheet("color: #888;")
        actions_layout.addWidget(self.status_label)
        
        layout.addWidget(actions_box)
        
        # === RESULTS TABLE ===
        results_box = QGroupBox("📊 Results")
        results_layout = QVBoxLayout(results_box)
        
        self.results_table = QTableWidget()
        self.results_table.setColumnCount(3)
        self.results_table.setHorizontalHeaderLabels(["File", "Status", "Details"])
        self.results_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
        self.results_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeToContents)
        self.results_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.Stretch)
        self.results_table.setAlternatingRowColors(True)
        results_layout.addWidget(self.results_table)
        
        # Summary
        self.summary_label = QLabel("")
        self.summary_label.setStyleSheet("font-weight: bold; margin-top: 8px;")
        results_layout.addWidget(self.summary_label)
        
        layout.addWidget(results_box, 1)
    
    def _browse_folder(self):
        path = QFileDialog.getExistingDirectory(self, "Select Papers Folder")
        if path:
            self.folder_edit.setText(path)
    
    def _start_scan(self):
        folder = self.folder_edit.text().strip()
        if not folder or not Path(folder).exists():
            QMessageBox.warning(self, "Invalid Folder", "Please select a valid folder.")
            return
        
        # Clear previous results
        self.results_table.setRowCount(0)
        self._results = []
        
        # UI state
        self.scan_btn.setEnabled(False)
        self.stop_btn.setEnabled(True)
        self.progress_bar.setVisible(True)
        self.progress_bar.setRange(0, 100)
        
        # Start worker
        self.worker = MermaidWorker(
            self.mermaid_engine,
            folder,
            inject_inline=self.inject_check.isChecked(),
            export_png=self.png_check.isChecked()
        )
        self.worker.progress.connect(self._on_progress)
        self.worker.file_done.connect(self._on_file_done)
        self.worker.finished.connect(self._on_finished)
        self.worker.start()
    
    def _stop_scan(self):
        if self.worker:
            self.worker.stop()
            self.status_label.setText("Stopping...")
    
    def _on_progress(self, current: int, total: int, filename: str):
        percent = int((current / total) * 100) if total > 0 else 0
        self.progress_bar.setValue(percent)
        self.status_label.setText(f"Processing {current}/{total}: {filename}")
    
    def _on_file_done(self, filename: str, success: bool, message: str):
        row = self.results_table.rowCount()
        self.results_table.insertRow(row)
        
        self.results_table.setItem(row, 0, QTableWidgetItem(filename))
        
        status = "✅" if success else "⚠️"
        status_item = QTableWidgetItem(status)
        status_item.setTextAlignment(Qt.AlignCenter)
        self.results_table.setItem(row, 1, status_item)
        
        self.results_table.setItem(row, 2, QTableWidgetItem(message))
        
        # Scroll to bottom
        self.results_table.scrollToBottom()
        
        self._results.append({'file': filename, 'success': success, 'message': message})
    
    def _on_finished(self, successful: int, total: int):
        self.scan_btn.setEnabled(True)
        self.stop_btn.setEnabled(False)
        self.progress_bar.setVisible(False)
        
        self.status_label.setText(f"Complete!")
        self.status_label.setStyleSheet("color: #00d9ff;")
        
        self.summary_label.setText(
            f"✅ {successful} papers with diagrams  |  "
            f"⚠️ {total - successful} skipped  |  "
            f"📊 {total} total scanned"
        )
        
        if successful > 0:
            QMessageBox.information(
                self,
                "Generation Complete",
                f"Generated mermaid diagrams for {successful} papers.\n\n"
                f"PNGs saved to: O:\\00_MEDIA\\Mermaid"
            )
    
    def _combine_all(self):
        """Combine all diagrams into one master graph."""
        folder = self.folder_edit.text().strip()
        if not folder or not Path(folder).exists():
            QMessageBox.warning(self, "Invalid Folder", "Please select a valid folder first.")
            return
        
        self.status_label.setText("Combining all diagrams...")
        
        try:
            # Collect all tags from all files
            all_tags = []
            folder_path = Path(folder)
            
            for md_file in folder_path.rglob("*.md"):
                tags = self.mermaid_engine.extract_tags(md_file)
                all_tags.extend(tags)
            
            if not all_tags:
                QMessageBox.warning(self, "No Tags", "No semantic tags found in any papers.")
                return
            
            # Generate master mermaid
            title = "THEOPHYSICS MASTER - All Dependencies"
            mermaid_code = self.mermaid_engine.generate_mermaid_code(all_tags, title)
            inline = self.mermaid_engine.generate_inline_mermaid(all_tags, title)
            
            # Export master PNG
            output_name = f"MASTER_COMBINED_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
            png_path = self.mermaid_engine.export_to_png(mermaid_code, output_name)
            
            # Save master mermaid file
            master_md = Path(r"O:\00_MEDIA\Mermaid") / f"{output_name}.md"
            master_md.write_text(f"# {title}\n\n{inline}", encoding='utf-8')
            
            self.status_label.setText(f"Master diagram created: {output_name}")
            self.status_label.setStyleSheet("color: #00d9ff;")
            
            msg = f"Combined {len(all_tags)} tags from all papers.\n\n"
            if png_path:
                msg += f"PNG: {png_path}\n"
            msg += f"MD: {master_md}"
            
            QMessageBox.information(self, "Master Created", msg)
            
        except Exception as e:
            self.status_label.setText(f"Error: {e}")
            self.status_label.setStyleSheet("color: #e94560;")
            QMessageBox.critical(self, "Error", str(e))
    
    def _open_media_folder(self):
        media_path = Path(r"O:\00_MEDIA\Mermaid")
        media_path.mkdir(parents=True, exist_ok=True)
        os.startfile(str(media_path))
