import re
import uuid
from datetime import datetime
from pathlib import Path

def parse_appendix(appendix_content):
    equations = []
    variables = {}

    # Regex to find tensors and operators
    pattern = re.compile(r"#### (\d+\. .*?)\n\n(.*?)(?=\n#### |\n---|\Z)", re.S)
    
    for match in pattern.finditer(appendix_content):
        title_line = match.group(1)
        body = match.group(2)
        
        name_match = re.search(r"(.+?)\s+\(.*?\)", title_line)
        if not name_match:
            continue

        base_name = name_match.group(1).strip()

        # Try to infer a primary variable token from the body.
        main_var_match = re.search(r"-\s*(\S+)\s*=", body)
        if main_var_match:
            main_var = main_var_match.group(1).strip()
            if main_var not in variables:
                variables[main_var] = {'concept': base_name, 'source': 'Appendix_A_Mathematical_Foundations.md'}

        # Find equations in $$...$$
        latex_equations = re.findall(r"\$\$([^\$]+)\$\$", body)
        for i, eq in enumerate(latex_equations):
            eq_text = eq.strip()
            equations.append({
                'uuid': f"eq-{base_name.lower().replace(' ', '-')}-{i+1}",
                'name': f"{base_name} Equation {i+1}",
                'latex': f"`$$`{eq_text}`$$`",
                'summary': f"Equation related to {base_name}.",
                'source': 'Appendix_A_Mathematical_Foundations.md'
            })

        # Find simple definitions like G₀ = baseline grace
        def_pattern = re.compile(r"-\s*(\S+)\s*=\s*(.*?)\n")
        for def_match in def_pattern.finditer(body):
            var = def_match.group(1)
            concept = def_match.group(2).strip()
            if var not in variables:
                variables[var] = {'concept': concept, 'source': 'Appendix_A_Mathematical_Foundations.md'}

    return equations, list(variables.items())

def generate_markdown_tables(equations, variables):
    date_today = datetime.now().strftime("%Y-%m-%d")

    # Equations table
    eq_header = "| UUID | Name | LaTeX | English Summary | Source | Date Added |\n|---|---|---|---|---|---|"
    eq_rows = [
        f"| {e['uuid']} | {e['name']} | {e['latex']} | {e['summary']} | {e['source']} | {date_today} |"
        for e in equations
    ]
    eq_table = eq_header + "\n".join(eq_rows)

    # Variables table
    var_header = "| Variable | Concept | Definition Note | First Used |\n|---|---|---|---|"
    var_rows = [
        f"| {var} | {data['concept']} | {data['source']} | {date_today} |"
        for var, data in variables
    ]
    var_table = var_header + "\n".join(var_rows)

    return eq_table, var_table

def main():
    try:
        with open('02_LIBRARY/02_Master_Framework/Appendix_A_Mathematical_Foundations.md', 'r', encoding='utf-8') as f:
            content = f.read()
    except FileNotFoundError:
        print("Error: Appendix file not found.")
        return

    equations, variables = parse_appendix(content)
    eq_table, var_table = generate_markdown_tables(equations, variables)

    out_dir = Path('master-truth/math')
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(out_dir / 'equations-registry.md', 'w', encoding='utf-8') as f:
        f.write("# Equations Registry\n\n")
        f.write(eq_table)
        f.write("\n\n---\n*This registry is auto-generated by the Theophysics Research Manager.*")

    with open(out_dir / 'variables-registry.md', 'w', encoding='utf-8') as f:
        f.write("# Variables Registry\n\n")
        f.write(var_table)
        f.write("\n\n---\n*This registry is auto-generated by the Theophysics Research Manager.*")

    print(f"Successfully populated registries with {len(equations)} equations and {len(variables)} variables.")

if __name__ == "__main__":
    main()
